#docker-compose version
version: "3"
services:
  mysql-standalone:
    image: mysql:5.7
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=mma123
      - MYSQL_DATABASE=mma
    ports:
      - 3307:3306
    volumes:
      - testData:/var/lib/mysql
      
  springboot-app:
    #Build the image using the docker file which is in the current folder
    build: .
    container_name: springboot-app
    ports:
      - "9999:8181"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysql-standalone:3306/mma?autoReconnect=true&useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "mma123",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    depends_on:
      - mysql-standalone
volumes:
  testData: